1425   task 7
zarafshanejaz786/MyPortfolio pull request #8
Opened 2023-10-20 11:12 UTC by zarafshanejaz786

Ticket Link:
https://dev.azure.com/CodeNinjaConsulting/Talent%20Pool/_workitems/edit/1483

Create a new data view page and display some data in the table. The data shown must be fetched from an external API. Add a link to the data view page in the page’s header. The new page should also have the same header, with a link to go back to the portfolio page.  

This should consist of areas/concepts that are specified

Add a section to display a table with some data. Research and choose a public API that provides some data (e.g., JSONPlaceholder for mock data). 

Use the fetch API to retrieve data from the chosen API. 
Display the fetched data (e.g., posts, comments, or any relevant data) in a visually appealing table on the interactive web page.

2023-10-23 10:42 UTC, aaminbaig requested changes

2023-10-23 10:42 UTC, aaminbaig commented on DataView.css
> +  margin-top: 10px;
you've already used **margin: 10px** not sure if this is still needed?

2023-10-23 10:42 UTC, aaminbaig commented on Signup.js
Your PR shouldn't have irrelevant changes. 

Sign Up changes shouldn't be a part of this PR, makes it difficult for the reviewer to differentiate between the actual task changes and some other random changes, that have nothing to do with the PR.

2023-10-23 10:42 UTC, aaminbaig commented on DataView.js
> +      const first10Posts = data.slice(0, 10);
Is there a specific reason to slice the data?

2023-10-24 05:46 UTC, zarafshanejaz786 commented on DataView.js
> +      const first10Posts = data.slice(0, 10);
yes because there was a large number of data in response. that's why I sliced it.

2023-10-24 05:46 UTC, zarafshanejaz786 commented on Signup.js
Sorry for the inconvenience, actually my task 6 was not yet approved by the review that's why I couldn't merge it in the main.

2023-10-24 05:46 UTC, zarafshanejaz786 commented on DataView.css
> +  margin-top: 10px;
removed, this was mistakenly added, while I was pasting classes from my other style sheets.

2023-10-24 07:13 UTC, aaminbaig approved these changes

2023-10-24 12:19 UTC, merged